spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: ['health', 'togglz']